### ISSUE TITLE
Essay Boxes in Problems

### ISSUE THREAD

**Issue by bstone** [djhunter/webwork-open-problem-library#2]
@djhunter, I think it might be beneficial to not have essay box answers mixed with problems that WW can check. For example, 

`webwork-open-problem-library/Contrib/Westmont/ActiveCalculus/Preview_4_1/preview_4_1_abce.pg`

the first and last questions WW can check, but the second questions the instructor has to manually check. This means that the problem is not marked correct until the grader looks at it. The problem I have with this is that since the numbers are randomized, when checking, I have to look at each students question to make sure numerical answers are correct as well as the essay. I would much rather not have to worry about checking the numerics and only worry about the essay. The only way I know how to do this is by breaking the problem in to two. The same holds for 4.2.  Any thoughts? 

Also, I am teaching Calc II right now and started with Chapter 4. The students are to complete the preview questions before class and this is the main issue I am having right now.

**Comment by djhunter** [comment]
I thought that the objective answers were supposed to show up green if they
are right and red if they are wrong, so you don't have to think too hard.
Which WeBWorK version is your server using? I'm using 2.10.

But you are right, you still have to award scores manually when an essay
question is present. I'm test driving these problems this semester with 53
students, so that will give me a chance to see how annoying it is. I guess
it would be safer to make the essay questions separate, but I was trying to
create problems that could be used independently without including other
problems in the set.

**Comment by bstone** [comment]
The problems show up green to the students, but when grading the problems manually, the grader is not able (as far as I can tell) see if the problem is correct. I am using WW 2.10. I like the simplicity of making all the questions as one problem, but I think it makes it harder to grade if essay questions are mixed with non-essay questions. I should be starting on my chapter 5 stuff soon and I will see if I can create something that works for me.

**Comment by djhunter** [comment]
With Preview activity 1.5d, the right answers show up as green and the wrong answers show up as red. See the screenshot below. I'm not sure why Preview 4.2 isn't working this way. It looks like I used the same problem grader on both.
![screen shot 2015-09-12 at 9 36 36 pm](https://cloud.githubusercontent.com/assets/4453085/9835256/68cc0f1c-5996-11e5-8980-ffc2f8e12fe2.png)

**Comment by bstone** [comment]
Wow, that is subtle. I didn't even notice the difference in color. Thanks for pointing this out. This being the case, I am not sure we need  to make essays in separate problems.
